### ISSUE TITLE
TypeError: BitThumb.setApiKey is not a function

### ISSUE THREAD

**Issue by mattverse** [stegano/bithumb#8]
imported using the following code

`const BitThumb = require("bithumb");
`

tried calling the following method as mentioned in README
`Bithumb.setApiKey(`<Enter your API Key>`, `<Enter your API Secret Key>`);
`

but getting the following error
`(node:45770) UnhandledPromiseRejectionWarning: TypeError: BitThumb.setApiKey is not a function`

**Comment by stegano** [comment]
Hi @mattverse

Please try import library with the code below 😀
```ts
// ESM
import { Bithumb } from 'bithumb';
```
or
```ts
// CJS
const { Bithumb } = require('bithumb');
```

**Comment by mattverse** [comment]
Thank you! Would be awesome if you can add this to readme later on as well! Thank you!
